FROM python:3.11-slim

# Install redis
RUN apt-get update
RUN apt-get --assume-yes install redis

WORKDIR /training_log

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip --root-user-action=ignore
RUN pip install -r requirements.txt --root-user-action=ignore

COPY . .

EXPOSE 5000
