version: '3.8'

services:
  web:
    build:
      context: ./training_log
      dockerfile: Dockerfile
    command: gunicorn training_log.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 5000
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

  huey:
    build:
      context: ./training_log
      dockerfile: Dockerfile.huey
    command: python manage.py run_huey
    env_file:
      - .env
    depends_on:
      - web
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}

  cache:
    container_name: ${REDIS_HOST:-redis}
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data

volumes:
  static_volume:
  redisdata:
    driver: local
