version: '3.8'

services:
  web:
    build:
      context: ./training_log #build the image for the web service from the dockerfile in parent directory
      dockerfile: Dockerfile
    command: gunicorn sampleApp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/training_log/staticfiles
    expose:
      - 5000
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/training_log/staticfiles
    depends_on:
      - web


volumes:
  static_volume:
