# Generated by Django 4.2.3 on 2023-08-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0011_rename_session_trainingsession"),
        ("strava_import", "0005_stravatypemapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stravatypemapping",
            name="discipline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training.discipline",
            ),
        ),
    ]
