# Generated by Django 4.2.4 on 2023-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strava_import", "0008_stravaactivityimport_imported_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StravaRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_limit", models.IntegerField()),
                ("daily_limit", models.IntegerField()),
                ("short_limit_usage", models.IntegerField()),
                ("daily_limit_usage", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
