# Generated by Django 4.2.4 on 2023-09-13 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("strava_import", "0009_stravaratelimit"),
    ]

    operations = [
        migrations.CreateModel(
            name="StravaSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("callback_url", models.URLField()),
                ("verify_token", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[("AC", "Active"), ("CR", "Created")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StravaUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strava_id", models.BigIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
