# Generated by Django 4.2.4 on 2023-09-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strava_import", "0011_stravasubscription_strava_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravauser",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="premium",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="resource_status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="sex",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="summit",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
