# Generated by Django 4.2.4 on 2023-09-14 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strava_import", "0012_stravauser_city_stravauser_premium_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stravauser",
            old_name="resource_status",
            new_name="resource_state",
        ),
    ]
