# Generated by Django 4.2.4 on 2023-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strava_import", "0013_rename_resource_status_stravauser_resource_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravauser",
            name="firstname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="lastname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
