# Generated by Django 4.2.4 on 2023-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "strava_import",
            "0001_squashed_0014_stravauser_firstname_stravauser_lastname",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stravauser",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="profile",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="profile_medium",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stravauser",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
