# Generated by Django 4.2.4 on 2023-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "strava_import",
            "0016_stravasubscription_updated_at_stravauser_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stravasubscription",
            name="state",
            field=models.CharField(
                choices=[
                    ("AC", "Active"),
                    ("VA", "Validated"),
                    ("CR", "Created"),
                    ("IN", "Invalid"),
                ],
                max_length=2,
            ),
        ),
    ]
