# Generated by Django 4.2.4 on 2023-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strava_import", "0017_alter_stravasubscription_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="StravaEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField()),
                ("object_id", models.BigIntegerField()),
                ("aspect_type", models.CharField()),
                ("event_time", models.IntegerField()),
                ("owner_id", models.IntegerField()),
                ("subscription_id", models.IntegerField()),
                ("updates", models.JSONField()),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
