# Generated by Django 4.2.3 on 2023-08-02 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='Session',
        ),
    ]
