# Generated by Django 4.2.3 on 2023-08-02 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0003_alter_session_duration"),
    ]

    operations = []
