# Generated by Django 4.2.3 on 2023-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0004_auto_20230802_1120"),
    ]

    operations = []
