# Generated by Django 4.2.3 on 2023-08-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20230802_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
