# Generated by Django 4.2.3 on 2023-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_session_duration_session_average_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='strava_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
