# Generated by Django 4.2.3 on 2023-08-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0008_session_strava_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="training_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training.trainingtype",
            ),
        ),
    ]
