# Generated by Django 4.2.4 on 2023-08-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0011_rename_session_trainingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
