# Generated by Django 4.2.4 on 2023-08-22 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0012_trainingsession_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingsession",
            options={"ordering": ["-date"]},
        ),
    ]
