# Generated by Django 4.2.4 on 2023-09-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0013_alter_trainingsession_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionZones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_state", models.IntegerField(blank=True, null=True)),
                ("points", models.FloatField(blank=True, null=True)),
                ("sensor_based", models.BooleanField(default=True)),
                ("zone_type", models.CharField()),
                ("score", models.IntegerField(blank=True, null=True)),
                ("custom_zones", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.FloatField()),
                ("max", models.FloatField()),
                ("time", models.IntegerField()),
                (
                    "session_zones",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.sessionzones",
                    ),
                ),
            ],
        ),
    ]
