# Generated by Django 4.2.4 on 2023-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0014_sessionzones_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionzones",
            name="custom_zones",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
