# Generated by Django 4.2.4 on 2023-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_squashed_0015_alter_sessionzones_custom_zones"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="speed_type",
            field=models.CharField(
                choices=[("KM", "km/h"), ("MM", "min/100m"), ("MK", "min/km")],
                default="KM",
                max_length=2,
            ),
        ),
    ]
