# Generated by Django 4.2.4 on 2023-09-18 11:57

from django.db import migrations, models


def covnert_session_zone_type(apps, schema_editor):
    SessionZones = apps.get_model("training", "SessionZones")

    choice_mapping = {
        "heartrate": "HR",
        "heart_rate": "HR",
        "power": "PW",
        "pace": "PC",
    }

    for session_zone in SessionZones.objects.all():
        old_type = session_zone.zone_type
        new_type = choice_mapping[old_type]
        if new_type is not None:
            session_zone.zone_type = new_type
            session_zone.save()
        else:
            session_zone.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0016_discipline_speed_type"),
    ]

    operations = [
        migrations.RunPython(covnert_session_zone_type),
        migrations.AlterField(
            model_name="sessionzones",
            name="zone_type",
            field=models.CharField(
                choices=[("HR", "Heart rate"), ("PW", "Power"), ("PC", "Pace")],
                max_length=2,
            ),
        ),
    ]
