# Generated by Django 4.2.4 on 2023-09-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0018_auto_20230918_1413"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="excluded",
            field=models.BooleanField(default=False),
        ),
    ]
