# Generated by Django 4.2.4 on 2023-10-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0019_trainingsession_excluded"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="polyline",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MunicipalityVisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("municipality", models.CharField()),
                (
                    "training_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingsession",
                    ),
                ),
            ],
        ),
    ]
