# Generated by Django 4.2.4 on 2023-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0020_trainingsession_polyline_municipalityvisits"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="summary_polyline",
            field=models.CharField(blank=True, null=True),
        ),
    ]
